### PR TITLE
encode branch names

### PR DESCRIPTION
**Pull request by maxkostow**
This fixes a bug if your branch name contains a `+` or something the job name will be incorrect.

It might probably mess up the displayed job name on jenkins if they are not decoded from uri components.

### CODE REVIEW

**Comment by jamesob** [comment]
I think something screwy might happen [here](https://github.com/percolate/jennifer/blob/encode_branch_name/lib/integration.coffee#L136)

**Comment by jamesob** [comment]
like when it goes to delete the job by name, it won't find it... right?

**Comment by maxkostow** [comment]
It should work because `makePrJobName` and `makeBranchFromJob` are always (or should always be) used to match GH prs and jenkins jobs. They are the inverse of each other.

**Comment by maxkostow** [comment]
I guess I haven't looked into jenkins' API enough to know if the job ID used in the URI and name are exactly the same or if https://github.com/jansepar/node-jenkins-api is unfortunately conflating the two

**Comment by jamesob** [comment]
I think deletion should work given that `makeBranchFromJob` is used to compare a job name against incoming gh data

**Comment by jamesob** [comment]
let's give 'er a shot. thanks for the PR, @maxkostow :love_letter:

**Comment by maxkostow** [comment]
:kiss:

**Comment by jamesob** [comment]
max you're such a weirdo

On Tue, Jan 28, 2014 at 2:59 PM, Max Kostow notifications@github.comwrote:

> [image: :kiss:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/percolate/jennifer/pull/6#issuecomment-33518026
> .

## 

646.479.0143

**Pull request merged**
