### PR TITLE
Use Github Commit Status API

### PR DESCRIPTION
**Pull request by mattheath**
This uses Github's Commit Status API to update the commit status of the pull request on build completion, in addition to the existing behaviour of adding a comment. This adds a _status_ (success/failure) to the pull request, along with a basic description (could be improved!) and a link back to the Jenkins build. 

Further information on [Github's blog post](https://github.com/blog/1227-commit-status-api). Example below, although currently the description text will be 'The Jenkins build passed`

commit status api

### CODE REVIEW

**Comment by jamesob** [comment]
Looks great. Testing now.

**Comment by jamesob** [comment]
@mattheath Is this actually modifying commit statuses for you? I keep getting responses that look like

``` json
{"message": "Not Found"}
```

Maybe be a problem with my configuration, though.

**Comment by jamesob** [comment]
I'm assuming something is off on my end. At any rate, the PR looks good and doesn't break anything, so I'm going to merge.

**Comment by mattheath** [comment]
@jamesob I got that originally - it's a permission issue with the Github OAuth token - you need the `repo` or `repo:status` scope to set commit statuses on private repositories via the API, and I don't think this is assigned by default. As the request doesn't have access to the private repo it responds with a 404. Further info: http://developer.github.com/v3/oauth/#scopes

To add the `repo` scope to an existing authorization:
http://developer.github.com/v3/oauth/#update-an-existing-authorization

```
curl -XPATCH -d '{"add_scopes": ["repo"], "note": "jennifer commit status"}'  https://api.github.com/authorizations/:id
```

**Comment by jamesob** [comment]
@mattheath Thanks for the reply. Oddly enough, my token does have the `repo` OAuth scope, which supposedly implies `repo:status`. Might be an issue on Github's end.

``` sh

 ⇨  http POST -j "https://api.github.com/repos/percolate/[ ourrepo]/statuses/d8db86313fd5feaac0e94a87e3ddb9463255e4c4?access_token=[our oauth token]" state=success target_url="http://[our-jenkins]/job/pr_1110_api_bitly_publish_settings/2" description="The Jenkins build passed"

HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Fri, 08 Feb 2013 22:56:04 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 404 Not Found
X-OAuth-Scopes: repo
X-RateLimit-Limit: 5000
X-GitHub-Media-Type: github.beta
Cache-Control: 
X-Accepted-OAuth-Scopes: public_repo, repo, repo:status, delete_repo
X-Content-Type-Options: nosniff
X-RateLimit-Remaining: 4891
Content-Encoding: gzip

{
    "message": "Not Found"
}
```

**Comment by StefanAniff** [comment]
Hi,

Did you guys ever resolve the issue related to the 404, not found, message?  I keep getting it as well and I have the repo scope associated with my token.

Thanks in advance

**Comment by jamesob** [comment]
Hey, @StefanAniff.

I found that the user associated with the token that Jennifer was using was limited to read-only access for the repo, despite having all the right scopes associated with the token, which (I think) was causing the 404s. Does this relate to your problem at all?

**Pull request merged**
